subplot(2,1,1);
legend(...
    strcat('N=',num2str(Nvect(1))),...
    strcat('N=',num2str(Nvect(2))),...
    strcat('N=',num2str(Nvect(3))),...
    strcat('N=',num2str(Nvect(4))),...
    strcat('N=',num2str(Nvect(5))),...
    'Location', 'northwest');
subplot(2,1,2);
legend(...
    strcat('N=',num2str(Nvect(1))),...
    strcat('N=',num2str(Nvect(2))),...
    strcat('N=',num2str(Nvect(3))),...
    strcat('N=',num2str(Nvect(4))),...
    strcat('N=',num2str(Nvect(5))),...
    strcat('y_z_a_d'),...
    'Location', 'northwest');