subplot(2,1,1);
legend(...
    strcat('u_D_M_C|N=',num2str(Nvect(1))),...
    strcat('u_D_M_C|N=',num2str(Nvect(2))),...
    strcat('u_D_M_C|N=',num2str(Nvect(3))),...
    strcat('u_D_M_C|N=',num2str(Nvect(4))),...
    strcat('u_D_M_C|N=',num2str(Nvect(5))),...
    'Location', 'southeast');
subplot(2,1,2);
legend(...
    strcat('y_m_o_d|N=',num2str(Nvect(1))),...
    strcat('y_m_o_d|N=',num2str(Nvect(2))),...
    strcat('y_m_o_d|N=',num2str(Nvect(3))),...
    strcat('y_m_o_d|N=',num2str(Nvect(4))),...
    strcat('y_m_o_d|N=',num2str(Nvect(5))),...
    strcat('y_z_a_d'),...
    'Location', 'southeast');