subplot(2,1,1);
legend(...
    strcat('u_D_M_C|D=',num2str(D)),...
    'Location', 'southeast');
subplot(2,1,2);
legend(...
    strcat('y_m_o_d|D=',num2str(D)),...
    strcat('y_z_a_d'),...
    'Location', 'southeast');