subplot(2,1,1);
legend(...
    strcat('u_D_M_C|Nu=',num2str(Nuvect(1))),...
    strcat('u_D_M_C|Nu=',num2str(Nuvect(2))),...
    strcat('u_D_M_C|Nu=',num2str(Nuvect(3))),...
    strcat('u_D_M_C|Nu=',num2str(Nuvect(4))),...
    strcat('u_D_M_C|Nu=',num2str(Nuvect(5))),...
    'Location', 'southeast');
subplot(2,1,2);
legend(...
    strcat('y_m_o_d|Nu=',num2str(Nuvect(1))),...
    strcat('y_m_o_d|Nu=',num2str(Nuvect(2))),...
    strcat('y_m_o_d|Nu=',num2str(Nuvect(3))),...
    strcat('y_m_o_d|Nu=',num2str(Nuvect(4))),...
    strcat('y_m_o_d|Nu=',num2str(Nuvect(5))),...
    strcat('y_z_a_d'),...
    'Location', 'southeast');